import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import ast
import os


class SimulationPlotter:
    """
    A unified plotting engine that reads CSVs generated by EventLogger.
    Call generate_plot('plot_name') to render specific visualizations.
    """

    def __init__(self, base_filepath='scenario_report'):
        self.base_filepath = base_filepath

        # Load Vehicles Data
        v_path = f"{base_filepath}_vehicles.csv"
        if os.path.exists(v_path):
            self.df_vehicles = pd.read_csv(v_path)
            # Safely parse the string representation of lists back into actual lists
            self.df_vehicles['cargo_manifest'] = self.df_vehicles['cargo_manifest'].apply(ast.literal_eval)
        else:
            self.df_vehicles = None
            print(f"Warning: {v_path} not found.")

        # Load Orders Data
        o_path = f"{base_filepath}_orders.csv"
        if os.path.exists(o_path):
            self.df_orders = pd.read_csv(o_path)
        else:
            self.df_orders = None

    def generate_plot(self, plot_type: str, save_to_disk: bool = False, output_dir: str = "."):
        """
        Router method to generate plots by name.
        Available plot_types:
        - 'cargo_gantt': Fleet-wide Gantt chart of order holding times (Optimized).
        - 'state_timeline': Timeline of vehicle statuses (Idle, En Route, Halt) and node visits.
        """
        if plot_type == 'cargo_gantt':
            self._plot_cargo_gantt(save_to_disk, output_dir)
        elif plot_type == 'state_timeline':
            self._plot_state_timeline(save_to_disk, output_dir)
        else:
            print(f"Error: Unknown plot type '{plot_type}'.")

    def _plot_state_timeline(self, save_to_disk: bool, output_dir: str):
        """
        Generates a state timeline for each vehicle showing their status durations
        and intelligently annotates the node ID only when it changes.
        """
        if self.df_vehicles is None or self.df_vehicles.empty:
            print("No vehicle data available to plot state timeline.")
            return

        intervals = []
        node_annotations = []
        grouped = self.df_vehicles.groupby('vehicle_id')

        # 1. Process data into continuous state intervals and unique node visits
        for vehicle_id, group_data in grouped:
            group_data = group_data.sort_values(by='time')

            prev_time = None
            prev_status = None
            last_annotated_node = None

            for _, row in group_data.iterrows():
                curr_time = row['time']
                curr_status = str(row['status']).title()
                curr_node = row['current_node']

                # Record the duration of the previous state
                if prev_time is not None and prev_status is not None:
                    intervals.append({
                        'Vehicle': f"Vehicle {vehicle_id}",
                        'Start': prev_time,
                        'End': curr_time,
                        'Status': prev_status
                    })

                # Check if we moved to a new, valid node to place an annotation
                is_valid_node = pd.notna(curr_node) and str(curr_node).lower() != 'none'
                if is_valid_node and curr_node != last_annotated_node:
                    node_annotations.append({
                        'Vehicle': f"Vehicle {vehicle_id}",
                        'Time': curr_time,
                        'Node': curr_node
                    })
                    last_annotated_node = curr_node

                prev_time = curr_time
                prev_status = curr_status

        if not intervals:
            print("Not enough event data to plot state timelines.")
            return

        df_intervals = pd.DataFrame(intervals)

        # 2. Setup plotting colors
        color_map = {
            'Idle': '#B0BEC5',  # Blue-Gray
            'En Route': '#81C784',  # Soft Green
            'Halted': '#E57373',  # Soft Red
            'Loading': '#FFD54F',  # Yellow
            'Unloading': '#FFB74D'  # Orange
        }
        default_color = '#9E9E9E'

        # 3. Render the Plot
        fig, ax = plt.subplots(figsize=(14, 8))

        # Sort vehicles descending for Y-axis
        unique_vehicles = sorted(df_intervals['Vehicle'].unique(), reverse=True)

        for i, vehicle in enumerate(unique_vehicles):
            v_data = df_intervals[df_intervals['Vehicle'] == vehicle]

            for _, row in v_data.iterrows():
                duration = row['End'] - row['Start']
                # Skip 0-duration artifacts
                if duration <= 0:
                    continue

                color = color_map.get(row['Status'], default_color)

                # Draw state bar
                ax.barh(y=vehicle,
                        width=duration,
                        left=row['Start'],
                        height=0.5,
                        color=color,
                        edgecolor='black',
                        linewidth=0.5,
                        alpha=0.9)

        # 4. Add Node Annotations on top of the bars
        for ann in node_annotations:
            ax.text(x=ann['Time'],
                    y=ann['Vehicle'],
                    s=f" N:{int(ann['Node'])}",
                    va='bottom', ha='left',
                    fontsize=9, color='black', fontweight='bold',
                    bbox=dict(facecolor='white', alpha=0.5, edgecolor='none', pad=0.1))

        # 5. Formatting and Legend
        ax.set_xlabel("Simulation Time (s)", fontsize=12)
        ax.set_ylabel("Fleet Vehicles", fontsize=12)
        ax.set_title("Fleet State Timeline & Node Progression", fontsize=14)
        ax.grid(axis='x', linestyle='--', alpha=0.5)

        # Create custom legend based on the colors used
        legend_patches = [mpatches.Patch(color=color, label=status) for status, color in color_map.items()]
        ax.legend(handles=legend_patches, loc='upper right', bbox_to_anchor=(1.15, 1), title="Vehicle States")

        plt.tight_layout()

        # 6. Save or Show
        if save_to_disk:
            if not os.path.exists(output_dir):
                os.makedirs(output_dir)
            filename = os.path.join(output_dir, "gantt_fleet_state_timeline.png")
            plt.savefig(filename, bbox_inches="tight")
            print(f"Saved: {filename}")
        else:
            plt.show()

    def _plot_cargo_gantt(self, save_to_disk: bool, output_dir: str):
        """
        Generates a single Gantt chart for the entire fleet.
        Uses greedy lane assignment to ensure overlapping orders are stacked
        neatly without overlapping visually.
        """
        if self.df_vehicles is None or self.df_vehicles.empty:
            print("No vehicle data available to plot cargo Gantt.")
            return

        intervals = []
        grouped = self.df_vehicles.groupby('vehicle_id')

        # Collect timeline data across all vehicles
        for vehicle_id, group_data in grouped:
            group_data = group_data.sort_values(by='time')
            active_orders = {}  # Tracks {order_id: pickup_time}

            for _, row in group_data.iterrows():
                current_time = row['time']
                current_manifest = set(row['cargo_manifest'])

                # 1. Detect newly loaded orders
                for o_id in current_manifest:
                    if o_id not in active_orders:
                        active_orders[o_id] = current_time

                # 2. Detect unloaded orders
                removed_orders = []
                for o_id, start_time in active_orders.items():
                    if o_id not in current_manifest:
                        intervals.append({
                            'Vehicle': f"Vehicle {vehicle_id}",
                            'Order': o_id,
                            'Start': start_time,
                            'End': current_time
                        })
                        removed_orders.append(o_id)

                for o_id in removed_orders:
                    del active_orders[o_id]

            # 3. Handle orders still in the vehicle at the end of the simulation
            last_known_time = group_data['time'].max()
            for o_id, start_time in active_orders.items():
                intervals.append({
                    'Vehicle': f"Vehicle {vehicle_id}",
                    'Order': o_id,
                    'Start': start_time,
                    'End': last_known_time
                })

        if not intervals:
            print("No vehicles carried any cargo. Skipping plot.")
            return

        df_intervals = pd.DataFrame(intervals)

        # --- OPTIMIZATION: Greedy Lane Assignment ---
        # Sort by Vehicle, then by Start Time to assign non-overlapping lanes
        df_intervals = df_intervals.sort_values(by=['Vehicle', 'Start'])
        optimized_intervals = []

        for vehicle, group in df_intervals.groupby('Vehicle'):
            lanes_end_times = []  # Tracks when each lane becomes free

            for _, row in group.iterrows():
                assigned_lane = -1

                # Find the first available lane where the order can fit
                for i, lane_end in enumerate(lanes_end_times):
                    if lane_end <= row['Start']:
                        assigned_lane = i
                        lanes_end_times[i] = row['End']
                        break

                # If no lane is free, create a new one
                if assigned_lane == -1:
                    assigned_lane = len(lanes_end_times)
                    lanes_end_times.append(row['End'])

                row_dict = row.to_dict()
                row_dict['Lane'] = assigned_lane
                optimized_intervals.append(row_dict)

        df_opt = pd.DataFrame(optimized_intervals)

        # --- RENDER THE MASTER PLOT ---
        fig, ax = plt.subplots(figsize=(14, 8))

        unique_vehicles = df_opt['Vehicle'].unique()

        yticks = []
        yticklabels = []
        current_y_base = 0  # Starting Y coordinate

        for v in unique_vehicles:
            v_data = df_opt[df_opt['Vehicle'] == v]
            max_lane = v_data['Lane'].max()

            # Draw all intervals for this vehicle
            for _, row in v_data.iterrows():
                y_pos = current_y_base + row['Lane']
                duration = row['End'] - row['Start']

                ax.barh(y=y_pos,
                        width=duration,
                        left=row['Start'],
                        height=0.8,
                        color='skyblue',
                        edgecolor='black',
                        alpha=0.8)

                # Annotate the bar with the Order ID
                mid_point = row['Start'] + (duration / 2)
                ax.text(mid_point, y_pos, str(row['Order']),
                        ha='center', va='center', fontsize=8, color='black',
                        bbox=dict(facecolor='white', alpha=0.6, edgecolor='none', pad=0.3))

            # Calculate the center of this vehicle's block for the Y-axis label
            center_y = current_y_base + (max_lane / 2.0)
            yticks.append(center_y)
            yticklabels.append(v)

            # Draw a subtle separator line between vehicles
            ax.axhline(y=current_y_base - 0.5, color='gray', linestyle=':', alpha=0.4)

            # Move the base Y up for the next vehicle, adding a gap of 2 units
            current_y_base += max_lane + 2.0

        ax.set_yticks(yticks)
        ax.set_yticklabels(yticklabels)
        ax.set_xlabel("Simulation Time (s)", fontsize=12)
        ax.set_title("Fleet Cargo Manifest Timeline (Optimized Stack)", fontsize=14)
        ax.grid(axis='x', linestyle='--', alpha=0.7)

        plt.tight_layout()

        if save_to_disk:
            if not os.path.exists(output_dir):
                os.makedirs(output_dir)
            filename = os.path.join(output_dir, "gantt_fleet_cargo_optimized.png")
            plt.savefig(filename)
            print(f"Saved: {filename}")
        else:
            plt.show()