import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import ast
import os
import numpy as np


class SimulationPlotter:
    """
    A unified plotting engine that reads CSVs generated by EventLogger.
    Call generate_plot('plot_name') to render visualizations.
    """

    def __init__(self, base_filepath='scenario_report', plot_return=False):
        self.base_filepath = base_filepath

        def _safe_parse_manifest(val):
            if isinstance(val, list): return val
            if pd.isna(val) or str(val).strip() == "": return []
            try:
                return ast.literal_eval(str(val))
            except (ValueError, SyntaxError):
                return []

        v_path = f"{base_filepath}_vehicles.csv"
        if os.path.exists(v_path):
            self.df_vehicles = pd.read_csv(v_path)
            self.df_vehicles['cargo_manifest'] = self.df_vehicles['cargo_manifest'].apply(_safe_parse_manifest)
        else:
            self.df_vehicles = None
            print(f"Warning: {v_path} not found.")

        o_path = f"{base_filepath}_orders.csv"
        if os.path.exists(o_path):
            self.df_orders = pd.read_csv(o_path)
        else:
            self.df_orders = None
        self.plot_return = plot_return

    def generate_plot(self, plot_type: str, save_to_disk: bool = False, output_dir: str = "."):
        if plot_type == 'cargo_gantt':
            self._plot_cargo_gantt(save_to_disk, output_dir)
        elif plot_type == 'state_timeline':
            self._plot_state_timeline(save_to_disk, output_dir)
        else:
            print(f"Error: Unknown plot type '{plot_type}'.")

    def _plot_state_timeline(self, save_to_disk: bool, output_dir: str):
        if self.df_vehicles is None or self.df_vehicles.empty:
            print("No vehicle data available to plot state timeline.")
            return

        intervals = []
        node_annotations = []
        grouped = self.df_vehicles.groupby('vehicle_id')

        for vehicle_id, group_data in grouped:
            group_data = group_data.reset_index().sort_values(by=['time', 'index'])
            prev_time, prev_status, last_annotated_node = None, None, None

            for _, row in group_data.iterrows():
                curr_time = row['time']
                curr_status_raw = str(row['status']).lower()
                curr_node = row['current_node']

                if prev_time is not None and prev_status is not None:
                    # Capture the return trip interval
                    status_to_plot = prev_status
                    if curr_status_raw == 'returned':
                        status_to_plot = 'Returning'

                    intervals.append({
                        'Vehicle': f"Vehicle {vehicle_id}",
                        'Start': prev_time, 'End': curr_time, 'Status': status_to_plot
                    })

                is_valid_node = pd.notna(curr_node) and str(curr_node).lower() != 'none'
                if is_valid_node and curr_node != last_annotated_node:
                    node_annotations.append({'Vehicle': f"Vehicle {vehicle_id}", 'Time': curr_time, 'Node': curr_node})
                    last_annotated_node = curr_node

                prev_time, prev_status = curr_time, curr_status_raw.title()

        if not intervals: return
        df_intervals = pd.DataFrame(intervals)

        color_map = {
            'Idle': '#B0BEC5', 'En Route': '#81C784', 'Returning': '#4FC3F7',
            'Halted': '#E57373', 'Loading': '#FFD54F', 'Unloading': '#FFB74D'
        }

        fig, ax = plt.subplots(figsize=(14, 8))
        unique_vehicles = sorted(df_intervals['Vehicle'].unique(), reverse=True)

        for vehicle in unique_vehicles:
            v_data = df_intervals[df_intervals['Vehicle'] == vehicle]
            for _, row in v_data.iterrows():
                duration = row['End'] - row['Start']
                if duration <= 0: continue
                ax.barh(y=vehicle, width=duration, left=row['Start'], height=0.5,
                        color=color_map.get(row['Status'], '#9E9E9E'), edgecolor='black', linewidth=0.5)

        for ann in node_annotations:
            ax.text(x=ann['Time'], y=ann['Vehicle'], s=f" N:{int(ann['Node'])}", va='bottom', fontsize=9,
                    fontweight='bold')

        # --- MODIFICATION: Dual-Grid (Manual Implementation) ---
        max_x = df_intervals['End'].max()
        # Set Major Ticks (Every 100)
        ax.set_xticks(np.arange(0, max_x + 100, 100))
        # Set Minor Ticks (Every 10)
        ax.set_xticks(np.arange(0, max_x + 10, 10), minor=True)

        # Style Major: Darker, Solid/Dashed
        ax.grid(which='major', axis='x', linestyle='-', color='#757575', alpha=0.7)
        # Style Minor: Lighter, Dotted
        ax.grid(which='minor', axis='x', linestyle=':', color='#BDBDBD', alpha=1)

        ax.set_xlabel("Simulation Time (s)")
        ax.set_ylabel("Fleet Vehicles")
        ax.set_title("Fleet State Timeline & Node Progression")
        legend_patches = [mpatches.Patch(color=color, label=status) for status, color in color_map.items()]
        ax.legend(handles=legend_patches, loc='upper right', bbox_to_anchor=(1.15, 1))
        plt.tight_layout()

        if save_to_disk:
            plt.savefig(os.path.join(output_dir, "gantt_fleet_state_timeline.png"), bbox_inches="tight")
        else:
            plt.show()

    def _plot_cargo_gantt(self, save_to_disk: bool = False, output_dir: str = "."):
        if self.df_vehicles is None or self.df_vehicles.empty: return

        intervals = []
        grouped = self.df_vehicles.groupby('vehicle_id')

        for vehicle_id, group_data in grouped:
            group_data = group_data.reset_index().sort_values(by=['time', 'index'])
            active_orders = {}
            for _, row in group_data.iterrows():
                current_time, current_manifest = row['time'], set(str(item) for item in row['cargo_manifest'])
                for o_id in current_manifest:
                    if o_id not in active_orders: active_orders[o_id] = current_time
                removed = []
                for o_id, start_time in active_orders.items():
                    if o_id not in current_manifest:
                        intervals.append({'Vehicle': f"Vehicle {vehicle_id}", 'Order': o_id,
                                          'Start': start_time, 'End': current_time, 'IsReturn': False})
                        removed.append(o_id)
                for o_id in removed: del active_orders[o_id]

            # Final Return Leg detection
            returned_rows = group_data[group_data['status'].str.lower() == 'returned']
            if not returned_rows.empty:
                pos = group_data.index.get_loc(returned_rows.index[0])
                if pos > 0:
                    intervals.append({'Vehicle': f"Vehicle {vehicle_id}", 'Order': 'Return Leg',
                                      'Start': group_data.iloc[pos - 1]['time'],
                                      'End': group_data.iloc[pos]['time'], 'IsReturn': True})

        if not intervals: return
        df_intervals = pd.DataFrame(intervals)
        df_intervals['Duration'] = df_intervals['End'] - df_intervals['Start']
        df_intervals = df_intervals[df_intervals['Duration'] > 0]

        df_intervals = df_intervals.sort_values(by=['Vehicle', 'Start'])
        optimized_intervals = []
        for vehicle, group in df_intervals.groupby('Vehicle'):
            ends = []
            for _, row in group.iterrows():
                lane = -1
                for i, e in enumerate(ends):
                    if e <= row['Start']: lane = i; ends[i] = row['End']; break
                if lane == -1: lane = len(ends); ends.append(row['End'])
                d = row.to_dict();
                d['Lane'] = lane;
                optimized_intervals.append(d)

        df_opt = pd.DataFrame(optimized_intervals)
        fig, ax = plt.subplots(figsize=(14, 8))
        unique_vehicles = sorted(df_opt['Vehicle'].unique(), reverse=True)
        current_y_base, yticks, yticklabels = 0, [], []

        for v in unique_vehicles:
            v_data = df_opt[df_opt['Vehicle'] == v]
            max_lane = v_data['Lane'].max()
            for _, row in v_data.iterrows():
                y_pos = current_y_base + row['Lane']
                color = '#FFA726' if row.get('IsReturn') else 'skyblue'
                ax.barh(y=y_pos, width=row['Duration'], left=row['Start'], height=0.8, color=color, edgecolor='black')
                ax.text(row['Start'] + (row['Duration'] / 2), y_pos, str(row['Order']), ha='center', va='center',
                        fontsize=8)

            yticks.append(current_y_base + (max_lane / 2.0))
            yticklabels.append(v)
            ax.axhline(y=current_y_base - 0.5, color='gray', linestyle=':', alpha=0.4)
            current_y_base += max_lane + 2.0

        # --- MODIFICATION: Dual-Grid (Manual Implementation) ---
        max_x = df_opt['End'].max()
        ax.set_xticks(np.arange(0, max_x + 100, 100))
        ax.set_xticks(np.arange(0, max_x + 10, 10), minor=True)
        ax.grid(which='major', axis='x', linestyle='-', color='#757575', alpha=0.7)
        ax.grid(which='minor', axis='x', linestyle=':', color='#BDBDBD', alpha=1)

        ax.set_yticks(yticks)
        ax.set_yticklabels(yticklabels)
        ax.set_xlabel("Simulation Time (s)");
        ax.set_title("Fleet Cargo Manifest Timeline")
        plt.tight_layout()

        if save_to_disk:
            plt.savefig(os.path.join(output_dir, "gantt_fleet_cargo_optimized.png"))
        else:
            plt.show()